---
- block:
    - include: disable_policy.yml
  when: cf_disable_stack_policy | default(False) | bool

- block:
    - include: build.yml
    - include: generator.yml
    - include: s3.yml
      when: cf_upload_s3 | default(True) | bool
    - include: costs.yml
      when: cf_upload_s3 | default(True) | bool and cf_calculate_costs | default(False) | bool
    - include: keypair.yml
    - include: cloudformation.yml
    - include: outputs.yml
      when: cf_upload_s3 | default(True) | bool
  always:
    - include: enable_policy.yml
      when: cf_disable_stack_policy is defined
  when: not cf_delete_stack | default(False) | bool

- block:
    - include: delete.yml
  when: cf_delete_stack | default(False) | bool