---
cf_cloudwatch_ec2_logs_policy: 
  PolicyName: CloudWatchLogs
  PolicyDocument:
    Version: "2012-10-17"
    Statement:
      - Effect: Allow
        Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "logs:DescribeLogStreams"
        Resource: { "Fn::Join": [":", [ 
          "arn:aws:logs", { "Ref": "AWS::Region" }, { "Ref": "AWS::AccountId" }, 
          "log-group", "{{ stack.name + '*'}}"
          ] ] }
cf_s3_bucket_mappings:
  "706286425777": dev-ytech-cloudformation-templates
  "801225830213": prod-ytech-cloudformation-templates
  "847222289464": sandbox-ytech-cloudformation-templates
  "639534165454": dr-ytech-cloudformation-templates
  
cf_default_stack_policy: {
    "Statement" : [
      {
        "Effect" : "Allow",
        "Action" : "Update:*",
        "Principal": "*",
        "Resource" : "*"
      }
    ]
  }
cf_globals_iam_credential_store_policy: |
  {
    "PolicyName": "credential-store",
    "PolicyDocument": {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "ReadOnlyAccessToCredentialStore",
          "Effect": "Allow",
          "Action": [
              "dynamodb:GetItem",
              "dynamodb:BatchGetItem",
              "dynamodb:Scan",
              "dynamodb:Query"
          ],
          "Resource": { "Fn::Join" : 
            ["", 
              [ 
                "arn:aws:dynamodb:", 
                { "Ref" : "AWS::Region" }, ":",
                { "Ref" : "AWS::AccountId" },
                ":table/", 
                { "Ref": "CredentialStore" }
              ]
            ] 
          }
        }
      ]
    }
  }

